require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'bin/bundle'

Metrics/BlockLength:
  Exclude:
    - 'spec/concepts/**/*'
    - 'spec/graphql/**/*'
    - 'app/graphql/errors.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/support/graphql/mutation_helpers/*'
    - 'spec/support/graphql/query_helpers/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/concepts/**/*'
    - 'spec/graphql/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: nested
  SupportedStyles:
    - nested
    - compact

Style/Documentation:
  Enabled: false
